### ISSUE TITLE
AttributeError: 'Worksheet' object has no attribute 'set_column'.

### ISSUE THREAD

**Issue by Lyreplus** [ardubev16/cineca-coursecatalogue-excel#1]
I was trying to use the main python script by invoking it with this command
`python3 main.py file.xlsx -l it`
Once I select my degree, the department, the course and then the study path, it appears this traceback

```
Traceback (most recent call last):
  File "/home/lyreplus/repositories/cineca-coursecatalogue-excel/main.py", line 142, in <module>
    save_to_xlsx(args.filename, courses)
  File "/home/lyreplus/repositories/cineca-coursecatalogue-excel/main.py", line 112, in save_to_xlsx
    writer.sheets["Sheet1"].set_column(col_idx, col_idx, column_width)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Worksheet' object has no attribute 'set_column'. Did you mean: 'max_column'?
```

I see that the error is that it is using an attribute that doesn't exist. It is a problem of the code or perhaps a difference between versions of python?

I'm using Python 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] on linux

**Comment by silvanusbordignon** [comment]
Does the error persist after installing the module `xlsxwriter`? Found this fix [here](https://stackoverflow.com/a/73642749) after incurring in the same problem this morning; was about to open a PR

**Comment by ardubev16** [comment]
Yep, there are two main engines to generate [excels with Pandas](https://pandas.pydata.org/docs/reference/api/pandas.ExcelWriter.html#pandas-excelwriter). I initially had both installed so I didn't notice that `openpyxl` doesn't have `set_column`. I just commited the fix, let me know if it works!
